# TCP configuration for headlines client
server:
  mode: tcp
  host: inference-service
  port: 50051
  max_workers: 10
  max_message_size: 10485760

# FinnHub configuration
symbols:
  - AAPL
  - MSFT

poll_interval: 2
